version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5433:5432"
    expose:
      - 5433
    networks:
      - icommerce  
      
  elasticsearch:
    image: elasticsearch:7.17.4
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
      - "9300"
    networks:
      - icommerce
    healthcheck:
      test: "curl -f http://localhost:9200 || exit 1"
       
networks:
  icommerce:      